# Purpose: PR Pipeline
#
# Uses dotnet test to run all *.UnitTests.dll;*.SystemTests.dll
#
trigger: none
pr: none

schedules:
- cron: "0 15 * * 0"
  displayName: "Weekly Sunday Build at 3pm GMT"
  branches:
    include: "master"
  always: true

name: 1.0$(Rev:.r)

variables:
  - name: Build.Configuration
    value: Release
  - name: YASF_TEST_EXECUTION_CONTEXT
    value: empty    
  - name: YASF_BROWSERSETTINGS_FILES
    value: common-headless-chrome.json
  - name: YASF_REMOTEWEBDRIVERSETTINGS_FILES
    value: common-localhost-selenium.json
  - name: YASF_ENVIRONMENTSETTINGS_FILES
    value: internet.json
  - name: YASF_CONTROLSETTINGS_FILES
    value: common.json

stages:
- stage: Build
  jobs:
  - template: templates/job-build-and-test-framework.yml
    parameters:
       frameworkFolder: "NetCore-Selenium"

