# Runs the tests using Google Chrome and target http://the-internet.herokuapp.com on the Internet
#
# Implementation:
# 1. All work is executed on a Windows VM
# 2. The tests are run 'from the VM' against the real website on the Internet

trigger: none
pr: none

name: 1.0$(Rev:.r)

variables:
  - name: Build.Configuration
    value: Release
  - name: THEINTERNET_TEST_EXECUTION_CONTEXT
    value: empty    
  - name: THEINTERNET_BROWSERSETTINGS_FILES
    value: headless-chrome.json
  - name: THEINTERNET_REMOTEWEBDRIVERSETTINGS_FILES
    value: localhost-selenium.json
  - name: THEINTERNET_ENVIRONMENTSETTINGS_FILES
    value: internet.json
  - name: THEINTERNET_CONTROLSETTINGS_FILES
    value: default.json
  - name: TEST_TARGET_FOLDER
    value: NetCore-Selenium

stages:
- stage: Build
  jobs:
  - job: Build
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml&viewFallbackFrom=vsts#timeouts
    timeoutInMinutes: 12
    cancelTimeoutInMinutes: 2
    pool:
      vmImage: windows-2019

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Dotnet Restore'
      inputs:
        command: restore
        projects: '**/*.sln'
    - task: DotNetCoreCLI@2
      displayName: 'Dotnet Publish'
      inputs:
        command: publish
        publishWebProjects: false
        projects: |
           **/*.sln
        
        arguments: '--no-restore --configuration $(Build.Configuration)'
        zipAfterPublish: false  

    - powershell: 'Get-ChildItem -Recurse'
      workingDirectory: src/$(TEST_TARGET_FOLDER)
      displayName: 'PowerShell Script'

    - task: DotNetCoreCLI@2
      displayName: 'Run Raw SystemTests'
      inputs:
        command: custom
        custom: vstest
        arguments: '$(System.DefaultWorkingDirectory)/src/$(TEST_TARGET_FOLDER)/TheInternet.SystemTests.Raw/bin/$(Build.Configuration)/netcoreapp3.1/publish/TheInternet.SystemTests.Raw.dll --logger:"trx;LogFileName=TheInternet-Tests.trx"'
    
    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/TheInternet-Tests.trx'
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: '**/TheInternet-Tests.trx'
        failTaskOnFailedTests: true
        testRunTitle: 'TheInternet-Tests'
