# Runs the tests using Google Chrome and target http://localhost:9000
#
# Implementation:
# 1. All work is executed on a Ubuntu VM
# 2. The tests are run 'from the VM' against a container running the application

trigger: none
pr: none

name: 1.0$(Rev:.r)

variables:
  - name: Build.Configuration
    value: Release
  - name: YASF_TEST_EXECUTION_CONTEXT
    value: empty    
  - name: YASF_BROWSERSETTINGS_FILES
    value: common-headless-chrome.json
  - name: YASF_REMOTEWEBDRIVERSETTINGS_FILES
    value: common-localhost-selenium.json
  - name: YASF_ENVIRONMENTSETTINGS_FILES
    value: internet-localhost.json
  - name: YASF_CONTROLSETTINGS_FILES
    value: common.json

stages:
- stage: Build
  jobs:
  - template: templates/job-internet-localhost.yml
    parameters:
       frameworkFolder: "NetCore-Selenium-3-141"
