# Purpose: PR Pipeline
#
# Uses dotnet test to run all *.UnitTests.dll;*.SystemTests.dll
#
trigger: none
pr:
- master

name: 1.0$(Rev:.r)

variables:
  - name: Build.Configuration
    value: Release
  - name: THEINTERNET_TEST_EXECUTION_CONTEXT
    value: empty    
  - name: THEINTERNET_BROWSERSETTINGS_FILES
    value: common-headless-chrome.json
  - name: THEINTERNET_REMOTEWEBDRIVERSETTINGS_FILES
    value: common-localhost-selenium.json
  - name: THEINTERNET_ENVIRONMENTSETTINGS_FILES
    value: internet.json
  - name: THEINTERNET_CONTROLSETTINGS_FILES
    value: common.json
  - name: TEST_TARGET_FOLDER
    value: NetCore-Selenium

stages:
- stage: Build
  jobs:
  - job: Build
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml&viewFallbackFrom=vsts#timeouts
    timeoutInMinutes: 12
    cancelTimeoutInMinutes: 2
    pool:
      vmImage: windows-2019

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Dotnet Restore'
      inputs:
        command: restore
        projects: '**/*.sln'
    - task: DotNetCoreCLI@2
      displayName: 'Dotnet Publish'
      inputs:
        command: publish
        publishWebProjects: false
        projects: |
           **/*.sln
        
        arguments: '--no-restore --configuration $(Build.Configuration)'
        zipAfterPublish: false  

    - task: DotNetCoreCLI@2
      displayName: 'Run Common.UnitTests'
      inputs:
        command: test
        workingDirectory: $(System.DefaultWorkingDirectory)/src/$(TEST_TARGET_FOLDER)/TheInternet.Common.UnitTests/bin/$(Build.Configuration)/netcoreapp3.1/publish
        arguments: TheInternet.Common.UnitTests.dll
        publishTestResults: true
        testRunTitle: Common.UnitTests

    - task: DotNetCoreCLI@2
      displayName: 'Run Common.SystemTests'
      inputs:
        command: test
        workingDirectory: $(System.DefaultWorkingDirectory)/src/$(TEST_TARGET_FOLDER)/TheInternet.Common.SystemTests/bin/$(Build.Configuration)/netcoreapp3.1/publish
        arguments: TheInternet.Common.SystemTests.dll
        publishTestResults: true
        testRunTitle: Common.SystemTests        

    - task: DotNetCoreCLI@2
      displayName: 'Run ExtentReports.System Tests'
      inputs:
        command: test
        workingDirectory: $(System.DefaultWorkingDirectory)/src/$(TEST_TARGET_FOLDER)/TheInternet.Common.ExtentReports.SystemTests/bin/$(Build.Configuration)/netcoreapp3.1/publish
        arguments: TheInternet.Common.ExtentReports.SystemTests.dll
        publishTestResults: true
        testRunTitle: Common.ExtentReports.SystemTests
