# Purpose: PR Pipeline
#
# Uses dotnet test to run all *.UnitTests.dll;*.SystemTests.dll
#
trigger: none
pr:
- master

name: 1.0$(Rev:.r)

variables:
  - name: Build.Configuration
    value: Release
  - name: YASF_TEST_EXECUTION_CONTEXT
    value: empty    
  - name: YASF_BROWSERSETTINGS_FILES
    value: common-headless-chrome.json
  - name: YASF_REMOTEWEBDRIVERSETTINGS_FILES
    value: common-localhost-selenium.json
  - name: YASF_ENVIRONMENTSETTINGS_FILES
    value: internet.json
  - name: YASF_CONTROLSETTINGS_FILES
    value: common.json
  - name: TEST_TARGET_FOLDER
    value: NetCore-Selenium

stages:
- stage: Build
  jobs:
  - job: Build
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml&viewFallbackFrom=vsts#timeouts
    timeoutInMinutes: 12
    cancelTimeoutInMinutes: 2
    pool:
      vmImage: windows-2022

    steps:
    - template: templates/build-and-publish.yml
    - template: templates/execute-common-unit-tests.yml
    - template: templates/execute-common-system-tests.yml
    - template: templates/execute-common-extent-reports-system-tests.yml
